### ISSUE TITLE
lean-lede的目录的git pull的错误能否永久消除要怎么消除？

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#278]
vehxb@lean:~/lede$ cd ..
vehxb@lean:~$ cd lean-lede
vehxb@lean:~/lean-lede$ git pull
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Total 149 (delta 96), reused 96 (delta 96), pack-reused 53
Receiving objects: 100% (149/149), 31.09 KiB | 4.44 MiB/s, done.
Resolving deltas: 100% (106/106), completed with 85 local objects.
From https://github.com/Lienol/lean-lede
   3999bcc7..1c4ae206  master     -> origin/master
Your configuration specifies to merge with the ref 'refs/heads/dev'
from the remote, but no such ref was fetched.

**Comment by Lienol** [comment]
lean-lede 分支 使用强push提交
If one has cloned this repo, use git pull --rebase instead of git pull to sync.
In case of merging conflicts, simply drop the commit with git rebase --skip.
In case of leftover commits (that got removed after a force-push), issue git rebase -i origin/HEAD and remove the leftover commits.
